[package]
name = "p2p-chess"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chess = "3.2.0"
minifb = "0.19.3"
kira = "0.5.3"
anyhow = "1.0.41"
tokio = { version = "1.7.1", features = ["macros", "rt-multi-thread"] }
rand = "0.8.4"
png = "0.16.8"
