[package]
name = "networking"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tari_comms = { path = "../../../tari/tari/comms" }
tari_comms_dht = { path = "../../../tari/tari/comms/dht" }
tari_storage = { path = "../../../tari/tari/infrastructure/storage" }
tari_shutdown = { path = "../../../tari/tari/infrastructure/shutdown" }

anyhow = "1.0.41"
prost = "0.7.0"
rand = "0.8.4"
tokio = "1.7.1"
tower = { version = "0.4", features = ["util"] }
lmdb-zero = "0.4.4"
